name: Metrics
on:
  # Lines below let you run workflow manually and on each commit (optional)
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # See action.yml for all options
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}
          user: AzharRizkiZ
          plugin_achievements: yes
          plugin_achievements_secrets: yes      # Display unlocked secrets achievements
          plugin_achievements_display: compact  # Use compact display
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year # Display full year instead of half year
          plugin_pagespeed: yes
          plugin_pagespeed_token: ${{ secrets.PAGESPEED_TOKEN }}
          plugin_languages: yes
          plugin_languages_ignored: html, css, scss, smarty, tex, jupyter notebook
          plugin_languages_details: bytes-size, percentage
          #plugin_languages_skipped: 
