name: Generate README.md File

on:
  workflow_dispatch:
  schedule:
    - cron: '9 */6 * * *'

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.11']

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
      - name: Generate README
        run: python generate.py

      - name: Commit README
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git checkout -b update
          git add .
          git commit -m "feat: update README"
          git push -u https://${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git update
          echo "${{ secrets.METRICS_TOKEN }}" | gh auth login --with-token
          gh pr create --head update --fill
          gh pr review --comment -b "PR I"
          gh pr review --comment -b "PR II"
          gh pr merge -d -m
